[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5066

[auth1000]
type=auth
auth_type=userpass
password=shield123
username=1000

[1000]
type=aor
max_contacts=1

[endpoint-1000]
type=endpoint
context=shieldcall-inbound
disallow=all
allow=ulaw
auth=auth1000
outbound_auth=auth1000
aors=1000
direct_media=no